const REACT_QUERY_KEY = {
  STUDYLOG: 'STUDYLOG',
  QUIZ: 'QUIZ',
  QUIZZES: 'QUIZZES',
  ESSAY_ANSWER: 'ESSAY_ANSWER',
  QUIZ_ANSWERS: 'QUIZ_ANSWERS',
  ESSAY_ANSWER_FILTER_LIST: 'ESSAY_ANSWER_FILTER_LIST',
};

export default REACT_QUERY_KEY;
