spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comment: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/prod
    enabled: true

security:
  jwt:
    token:
      secret-key: secret_key
      expire-length: 3600000
  oauth2:
    client:
      provider:
        github:
          token-uri: https://github.com/login/oauth/access_token
          user-info-uri: https://api.github.com/user
      registration:
        github:
          client-id: client_id
          client-secret: client_secret

github:
  client:
    id: client_id
    secret: client_secret
  url:
    access-token: https://github.com/login/oauth/access_token
    profile: https://api.github.com/user