spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comment: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/prod
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:13306/prolog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  jwt:
    token:
      secret-key: secret_key
      expire-length: 3600000

github:
  client:
    id: f91b56445e08d44adb76
    secret: f02769f780ed3d40f9db9283f5b7cc79ecf9074e
  url:
    access-token: https://github.com/login/oauth/access_token
    profile: https://api.github.com/user

elasticsearch:
  host: 127.0.0.1
  port: 9200

application:
  url: http://127.0.0.1:8080
